id = "mqagent"
version = "1.1.0"
name = { en = "MQAgent", zh = "MQAgent" }
logo = "/res/logo.png"
description = "3v3 SoccerSim Agent written in Python"
entry = "src/main.py:SoccerSimAgent"
debuggable = true

[requirements]
min_api_level = 10700
models = [ "Booster K1" ]