# This Docker image builds off Booster's "agent-dev" image with the 3v3 match scene's detection_extension added at build time to get access to the vision portion of the robotics pipeline.
#
# Additionally, Booster's own image lives on a registry blocked on some networks. 
# Building this image and pushing to DockerHub provides an alternative way to access the image.

##### STUDENTS #####
# See docker/README.md on how to set up your project to use the image!

ARG BASE_IMAGE=booster-robotics-registry.cn-beijing.cr.aliyuncs.com/agent-dev/agent-dev:0.7.21-alpha-humble
FROM ${BASE_IMAGE}

COPY scripts/patch_match_scene_detection.py /tmp/patch_match_scene_detection.py
RUN python3 /tmp/patch_match_scene_detection.py \
        --file /usr/local/booster_robot/booster_robocup_sim/mjcf/football_match_pitch_6_K1.extensions.xml \
    && rm /tmp/patch_match_scene_detection.py
